= 15-Minute-Cities (Project 10)

Group 4 (Jan Klüwer, Markus Maas Philipp Marder, Tristan Mertins & mentor Romain Deschamps)

== Instructions
.Steps to execute
. Download our repository
. Open _5minapp.py_ in your IDE (e.g. PyCharm) and run the file
. The Python Console should print out a command like the following: 
streamlit run C:/Users/trist/PycharmProjects/15min_cities/15minapp.py +
Copy this command, paste it into your Terminal and press enter.
. The Terminal will generate a Local URL which should automatically open in your browser. If not copy it and open the URL manually.
. Welcome to pur app. On the left site of the page you can choose your preferences. Tick your favorite facilities/ amenities and use the scale to determine how important they are to you.
. Now type in the address to be viewed and click on _Create Map_
. You should see all amenities of your interest in a 15-minute radius starting from your entered location
 

All the versions we used are written down in _requirements.txt_
